object Modules {
    const val app = ":app"
    const val core = ":core"
    const val features = ":features"
    const val featInAppReview = ":features:feat-inappreview"
    const val corePreferences = ":core:core-preferences"
    const val coreUi = ":core:core-ui"
    const val coreCommon = ":core:core-common"
    const val coreLogger = ":core:core-logger"
    const val coreLocation = ":core:core-location"
    const val coreConnectivity = ":core:core-connectivity"
    const val coreDatabase = ":core:core-database"
    const val corePermission = ":core:core-permission"
    const val coreNetwork = ":core:core-network"
    const val coreModels = ":core:core-models"
    const val coreRepository = ":core:core-repository"
}